export const OutputState = {
  OBS_WEBSOCKET_OUTPUT_STARTING: 'OBS_WEBSOCKET_OUTPUT_STARTING',
  OBS_WEBSOCKET_OUTPUT_STARTED: 'OBS_WEBSOCKET_OUTPUT_STARTED',
  OBS_WEBSOCKET_OUTPUT_STOPPING: 'OBS_WEBSOCKET_OUTPUT_STOPPING',
  OBS_WEBSOCKET_OUTPUT_STOPPED: 'OBS_WEBSOCKET_OUTPUT_STOPPED',
  OBS_WEBSOCKET_OUTPUT_PAUSED: 'OBS_WEBSOCKET_OUTPUT_PAUSED',
  OBS_WEBSOCKET_OUTPUT_RESUMED: 'OBS_WEBSOCKET_OUTPUT_RESUMED',
} as const;
